# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run.
on:
  # Triggers the workflow on push only for the main branch
  push:
    branches:
      - release*
  pull_request:
    branches:
      - release*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clean
        if: always()
        run: ./gradlew clean
      - name: Assemble
        id: assemble
        if: always()
        run: ./gradlew app:assembleRelease
      - name: Archive Apk
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: |
            app/build/outputs/apk/**/*.apk
            app/build/outputs/mapping/**/*.txt



